/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_a12852_opencvtestdemo_tools_NativeHelp */

#ifndef _Included_com_example_a12852_opencvtestdemo_tools_NativeHelp
#define _Included_com_example_a12852_opencvtestdemo_tools_NativeHelp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_a12852_opencvtestdemo_tools_NativeHelp
 * Method:    testInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_a12852_opencvtestdemo_tools_NativeHelp_testInt
  (JNIEnv *, jclass);

/*
 * Class:     com_example_a12852_opencvtestdemo_tools_NativeHelp
 * Method:    testString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_a12852_opencvtestdemo_tools_NativeHelp_testString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_a12852_opencvtestdemo_tools_NativeHelp
 * Method:    setStudent
 * Signature: (Lcom/example/a12852/opencvtestdemo/entity/Student;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_a12852_opencvtestdemo_tools_NativeHelp_setStudent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_a12852_opencvtestdemo_tools_NativeHelp
 * Method:    getStudent
 * Signature: ()Lcom/example/a12852/opencvtestdemo/entity/Student;
 */
JNIEXPORT jobject JNICALL Java_com_example_a12852_opencvtestdemo_tools_NativeHelp_getStudent
  (JNIEnv *, jclass);

/*
 * Class:     com_example_a12852_opencvtestdemo_tools_NativeHelp
 * Method:    testBitMap
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_a12852_opencvtestdemo_tools_NativeHelp_testBitMap
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_example_a12852_opencvtestdemo_tools_NativeHelp
 * Method:    getHashMap
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_example_a12852_opencvtestdemo_tools_NativeHelp_getHashMap
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
